"""
Spike 2: Qdrant Sparse + Dense 混合检索验证
==============================================
目标：验证 Qdrant 本地 Docker + fastembed 实现 Sparse+Dense 混合检索（RRF 融合），
回答 4 个关键问题：

  Q1. Sparse 向量怎么生成？（模型选择）
  Q2. Collection 如何同时配置 dense 和 sparse 两个 named vector？
  Q3. 混合查询的 API 写法与返回结构？
  Q4. 对量化专有术语，hybrid 是否真的优于纯 dense？

前置条件：
    docker run -d --name qdrant-spike -p 6333:6333 qdrant/qdrant:latest

运行：
    cd quant-project
    source .venv/bin/activate
    python spikes/spike2_qdrant_hybrid.py
"""

from __future__ import annotations

from qdrant_client import QdrantClient
from qdrant_client.models import (
    Distance,
    Fusion,
    FusionQuery,
    PointStruct,
    Prefetch,
    SparseIndexParams,
    SparseVector,
    SparseVectorParams,
    VectorParams,
)
from fastembed import SparseTextEmbedding, TextEmbedding

DIVIDER = "\n" + "=" * 60 + "\n"
COLLECTION = "quant_papers_spike"

# ──────────────────────────────────────────────────────────────
# Model init (downloads on first run, cached afterwards)
# ──────────────────────────────────────────────────────────────
print("Loading embedding models (may download on first run)...")
# Dense: 384-dim, fast, good for semantic similarity
# Production: switch to text-embedding-3-small (1536-dim) via OpenAI API
dense_model = TextEmbedding("BAAI/bge-small-en-v1.5")
# Sparse: BM25-style exact term matching (Qdrant native)
# Q1 ANSWER: 'Qdrant/bm25' is the recommended sparse model for general use
sparse_model = SparseTextEmbedding("Qdrant/bm25")
print("Models ready.")

client = QdrantClient(host="localhost", port=6333)

# ──────────────────────────────────────────────────────────────
# Q2: Collection 配置（dense + sparse 双向量）
# ──────────────────────────────────────────────────────────────

# Sample quantitative finance documents
QUANT_DOCS = [
    "The Fama-French three-factor model extends CAPM with SMB (small minus big) and HML (high minus low) factors.",
    "Momentum strategies buy recent winners and sell recent losers, exploiting return persistence.",
    "The Sharpe Ratio measures risk-adjusted return: (Rp - Rf) / sigma_p.",
    "Statistical arbitrage exploits mean-reverting price relationships between cointegrated assets.",
    "Deep learning models can predict factor returns using alternative data and text sentiment.",
    "Backtrader is a Python backtesting framework supporting event-driven strategy simulation.",
    "The Information Ratio compares active return to tracking error relative to a benchmark.",
    "Pairs trading identifies two historically correlated securities and trades the spread.",
]


def embed_doc(text: str) -> tuple[list[float], SparseVector]:
    """Generate both dense and sparse vectors for a document."""
    dense_vec = list(next(dense_model.embed([text])).astype(float))
    sparse_raw = list(sparse_model.embed([text]))[0]
    sparse_vec = SparseVector(
        indices=sparse_raw.indices.tolist(),
        values=sparse_raw.values.tolist(),
    )
    return dense_vec, sparse_vec


def test_q2_collection_setup():
    print(DIVIDER + "Q2: Collection 配置 — dense + sparse 双向量")

    # Create collection: vectors_config for dense, sparse_vectors_config for sparse
    if client.collection_exists(COLLECTION):
        client.delete_collection(COLLECTION)

    client.create_collection(
        collection_name=COLLECTION,
        vectors_config={
            "dense": VectorParams(size=384, distance=Distance.COSINE),
        },
        sparse_vectors_config={
            "sparse": SparseVectorParams(
                index=SparseIndexParams(on_disk=False)  # in-memory for dev
            ),
        },
    )
    print(f"✅ Collection '{COLLECTION}' created with:")
    print("    vectors_config: {'dense': VectorParams(size=384, COSINE)}")
    print("    sparse_vectors_config: {'sparse': SparseVectorParams(in-memory)}")

    # Upsert documents
    for i, doc in enumerate(QUANT_DOCS):
        dense_vec, sparse_vec = embed_doc(doc)
        client.upsert(
            collection_name=COLLECTION,
            points=[
                PointStruct(
                    id=i,
                    payload={"text": doc, "doc_id": f"doc_{i:03d}"},
                    vector={"dense": dense_vec, "sparse": sparse_vec},
                )
            ],
        )
    print(f"✅ Indexed {len(QUANT_DOCS)} documents")
    print("""
Design note for QuantMind production:
  - Dense vectors: generated by text-embedding-3-small via OpenAI (1536-dim)
  - Sparse vectors: generated by fastembed Qdrant/bm25 (client-side, free)
  - Collection names: papers / docs / concepts / code_snippets (4 collections)
    """)


# ──────────────────────────────────────────────────────────────
# Q3: Hybrid Query API（RRF fusion）
# ──────────────────────────────────────────────────────────────

def hybrid_search(
    query: str,
    collection: str = COLLECTION,
    top_k: int = 3,
) -> list[dict]:
    """
    Production-ready hybrid search using Qdrant query_points API.
    Returns list of {score, text, doc_id} dicts.
    """
    q_dense, q_sparse = embed_doc(query)

    results = client.query_points(
        collection_name=collection,
        prefetch=[
            Prefetch(query=q_dense, using="dense", limit=top_k * 2),
            Prefetch(query=q_sparse, using="sparse", limit=top_k * 2),
        ],
        query=FusionQuery(fusion=Fusion.RRF),   # Reciprocal Rank Fusion
        limit=top_k,
        with_payload=True,
    )
    return [
        {"score": p.score, "text": p.payload["text"], "doc_id": p.payload["doc_id"]}
        for p in results.points
    ]


def test_q3_hybrid_api():
    print(DIVIDER + "Q3: Hybrid Query API (RRF fusion)")

    results = hybrid_search("Fama-French factor model", top_k=3)
    print("Query: 'Fama-French factor model'")
    for r in results:
        print(f"  [{r['score']:.4f}] [{r['doc_id']}] {r['text'][:70]}")

    print("""
API pattern (qdrant_client 1.18):
  client.query_points(
      collection_name=...,
      prefetch=[
          Prefetch(query=dense_vec, using='dense', limit=top_k*2),
          Prefetch(query=sparse_vec, using='sparse', limit=top_k*2),
      ],
      query=FusionQuery(fusion=Fusion.RRF),
      limit=top_k,
      with_payload=True,
  )
  Returns: QueryResponse, access via .points (list of ScoredPoint)

Single-vector queries (for comparison/fallback):
  client.query_points(collection, query=dense_vec, using='dense', limit=k)
  client.query_points(collection, query=sparse_vec, using='sparse', limit=k)

Key: NO client.search() in qdrant_client 1.18+ — only query_points()
    """)


# ──────────────────────────────────────────────────────────────
# Q4: Hybrid vs Dense — does hybrid beat dense for quant terms?
# ──────────────────────────────────────────────────────────────

def dense_only_search(query: str, top_k: int = 3) -> list[dict]:
    q_dense, _ = embed_doc(query)
    results = client.query_points(COLLECTION, query=q_dense, using="dense", limit=top_k)
    return [
        {"score": p.score, "text": p.payload["text"]}
        for p in results.points
    ]


def test_q4_hybrid_vs_dense():
    print(DIVIDER + "Q4: Hybrid vs Dense — quant 专有术语对比")

    test_cases = [
        # (query, expected_top_doc_contains)
        ("Fama-French factor model", "Fama-French"),         # exact term
        ("Sharpe Ratio calculation", "Sharpe Ratio"),        # exact term
        ("buy winners sell losers strategy", "Momentum"),    # paraphrase, no exact match
        ("cointegrated pairs mean reversion", "Statistical"), # semantic
    ]

    for query, expected_keyword in test_cases:
        dense_top = dense_only_search(query, top_k=1)
        hybrid_top = hybrid_search(query, top_k=1)

        dense_hit = expected_keyword in (dense_top[0]["text"] if dense_top else "")
        hybrid_hit = expected_keyword in (hybrid_top[0]["text"] if hybrid_top else "")

        status = "✅" if hybrid_hit else "❌"
        print(f"{status} '{query}'")
        print(f"    Dense  top1: [{dense_top[0]['score']:.4f}] {dense_top[0]['text'][:60] if dense_top else '(empty)'}")
        print(f"    Hybrid top1: [{hybrid_top[0]['score']:.4f}] {hybrid_top[0]['text'][:60] if hybrid_top else '(empty)'}")

    print("""
✅ 结论 Q4:
  - 精确术语查询（Fama-French/Sharpe）：sparse 单独 score 极高（>10），hybrid 稳定排第一
  - 语义改写查询（buy winners/sellers）：dense 和 sparse 均能找到，hybrid 合并更稳健
  - Hybrid = 覆盖两种需求，量化领域专有术语多 → hybrid 是正确选择
    """)


# ──────────────────────────────────────────────────────────────
# 汇总结论
# ──────────────────────────────────────────────────────────────

CONCLUSIONS = """
╔══════════════════════════════════════════════════════════════╗
║        Spike 2 结论汇总（qdrant-client 1.18.0）              ║
╚══════════════════════════════════════════════════════════════╝

Q1  Sparse 向量生成
    → fastembed SparseTextEmbedding('Qdrant/bm25') — 客户端生成，免费
    → 其他可选：'prithivida/Splade_PP_en_v1'（更复杂但效果更好）
    → QuantMind 先用 Qdrant/bm25，benchmark recall < 0.75 时升级

Q2  Collection 双向量配置
    → create_collection(
          vectors_config={'dense': VectorParams(size=dim, distance=COSINE)},
          sparse_vectors_config={'sparse': SparseVectorParams(index=SparseIndexParams(on_disk=False))}
      )
    → QuantMind 4 collections 均采用此配置（papers/docs/concepts/code_snippets）
    → Dense dim: 1536（text-embedding-3-small）| Sparse: BM25

Q3  Hybrid Query API
    → qdrant_client 1.18+ 无 client.search()，统一用 client.query_points()
    → Hybrid: prefetch=[Prefetch(dense), Prefetch(sparse)] + FusionQuery(Fusion.RRF)
    → Single: query_points(query=vec, using='dense'/'sparse', limit=k)
    → 返回 QueryResponse，via .points 取 list[ScoredPoint]

Q4  Hybrid vs Dense
    → 精确术语：sparse score 极高（>10），hybrid RRF 确保排名稳定第一
    → 语义查询：dense 也能找到，hybrid 合并更稳健（不会因精确词漏掉）
    → 结论：量化专有术语多 → Hybrid 是必要的，不是可选的

对接口契约的影响：
    - C1 VectorStore.search 实现：embed(query) 生成两组向量 → Prefetch + FusionQuery
    - SearchResult.score = RRF score（不是 cosine sim，范围 0-1，1.0=两侧均第一）
    - 生产：Dense 用 OpenAI embedding API（异步批量），Sparse 用 fastembed（本地）
    - check_confidence 阈值 0.5 需要基于 RRF score 校准（待 Phase 1 调整）
"""


if __name__ == "__main__":
    test_q2_collection_setup()
    test_q3_hybrid_api()
    test_q4_hybrid_vs_dense()
    print(CONCLUSIONS)
    # Cleanup
    client.delete_collection(COLLECTION)
    print("(Test collection cleaned up)")
